version: "3.8"
services:
  gclone:
    image: rekulous/clonedrive-bot:latest
    build:
      context: .
    volumes:
      - ./rclone.conf:$HOME/.config/rclone/rclone.conf
      - ./accounts:/accounts
